# Generated by Django 4.1.3 on 2022-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bgImage',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='filter_explicit',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.URLField(default='https://kasmanninsurance.com/wp-content/uploads/2015/10/Car_with_Driver-Silhouette.svg-red.png'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='screen_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
