# Generated by Django 4.1.3 on 2022-12-09 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('car_year', models.IntegerField(max_length=150)),
                ('car_make', models.CharField(max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('car_trim', models.CharField(max_length=150)),
                ('weight', models.IntegerField()),
                ('powercc', models.IntegerField()),
                ('lkm', models.IntegerField()),
                ('powerps', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('compression', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
