# Generated by Django 4.1.3 on 2022-11-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redline', '0002_alter_customuser_options_customuser_bgimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Is_following',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
