# Generated by Django 4.1.3 on 2022-11-28 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redline', '0003_is_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.CharField(default='', max_length=200)),
                ('media_link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('explicit', models.BooleanField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
