# Generated by Django 4.1.3 on 2022-11-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redline', '0004_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Post_reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='redline.posts')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='redline.posts')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
