# Generated by Django 4.1.3 on 2022-11-29 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redline', '0005_alter_posts_options_post_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redline.posts')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
